services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-instance-runner-1
    entrypoint: [""]
    command: ["/bin/sh", "-c", "gitlab-runner register \
                                      --non-interactive \
                                      --url 'https://gitlab.nktech.online/' \
                                      --registration-token 'glrt-t3_L9CPDoCtLyyfVAeQQKhq' \
                                      --executor 'docker' \
                                      --docker-network-mode 'host' \
                                      --docker-image 'python:alpine' \
            && gitlab-runner run --user=gitlab-runner --working-directory=/etc/gitlab-runner"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    network_mode: 'host'
