services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - SUBDOMAINS=ptnr.duckdns.org
      - TOKEN=2626e18d-fadf-4ee1-90c7-0488d3b1ea24
      - UPDATE_IP=ipv4
      - LOG_FILE=false
    volumes:
      - ./duckdns/config:/config
    restart: unless-stopped
