global:
  scrape_interval: 2s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 192.168.1.92:9090

  - job_name: node_exporter
    static_configs:
      - targets:
          - 192.168.1.91:9100
          - 192.168.1.92:9100
          - 192.168.1.93:9100