services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - VERSION=docker
      - PLEX_CLAIM="claim-f7qFX7QCspuVXLzxR6gX"
    volumes:
      - ./plex/config:/config
      - /home/nani/Dev/MEDIA/marriage:/marriage
      - /home/nani/Dev/MEDIA/video_songs:/video_songs
      - /home/nani/Dev/MEDIA/Movies:/movies
      - /home/nani/Utils/Manali:/manali
    restart: unless-stopped
