networks:
  frontend:
    external: true

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    dns:
      - 8.8.8.8
      - 8.8.4.4
    privileged: true
    user: root
    ports:
      - 8082:8080
      - 50000:50000
    container_name: jenkins
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    restart: on-failure
    networks:
      - frontend
