networks:
  frontend:
    external: true

services:
  artifactory-service:
    image: docker.bintray.io/jfrog/artifactory-oss:7.71.5
    container_name: artifactory
    restart: always
    ports:
      - 8083:8081
      - 8084:8082
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    networks:
      - frontend

volumes:
  artifactory_data:
