---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Media:
  - Plex:
      icon: plex.svg
      server: 192.168.1.3
      href: https://plex.nanitech.duckdns.org/
      description: A Stream server for Photos and Videos
      widget:
        type: plex
        url: http://192.168.1.3:32400
        key: yZypTLZxZ_hz1dbvGoxf


- DataScraping:
  - Prometheus:
      icon: prometheus.png
      server: 192.168.1.90
      href: https://prometheus.nanitech.duckdns.org/
      description: Datasource tool for Grafana
      widget:
        type: prometheus
        url: http://192.168.1.90:9090

- Security and DNS:
  - authentik:
      icon: authentik.png
      server: 192.168.1.91
      href: https://authentik.nanitech.duckdns.org
      description: users and logins
      widget:
        type: authentik
        url: https://192.168.1.91:9444
        key: {{HOMEPAGE_VAR_AUTHETIK_ACCESS_KEY}}
  - pihole:
      icon: pihole.svg
      server: 192.168.1.91
      href: http://192.168.1.91/admin
      description: local DNS server
      widget:
        type: pihole
        url: http://192.168.1.91/admin

- Monitoring:
  - grafana:
      icon: grafana.svg
      server: 192.168.1.90
      href: https://grafana.nanitech.duckdns.org/
      description: Monitor Dashboards and DataSources
      widget:
        type: grafana
        url: http://192.168.1.90:3000
        username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
        password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}

  - kuma:
      icon: uptime-kuma.svg
      server: 192.168.1.90
      href: https://kuma.nanitech.duckdns.org/
      description: Monitor servers and services
      widget:
        type: uptimekuma
        url: http://192.168.1.90:3001
        slug: services

- Speed Monitor:
  - My Speed:
      icon: myspeed.svg
      server: 192.168.1.90
      href: https://myspeed.nanitech.duckdns.org/
      description: Internet speed test
      widget:
        type: myspeed
        url: http://192.168.1.90:5216

  - qBittorrent:
      icon: qbittorrent.svg
      server: 192.168.1.91
      href: https://qbittorrent.nanitech.duckdns.org/
      description: A torrent downloader
      widget:
        type: qbittorrent
        url: http://192.168.1.91:8080
        username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
        password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}

- Container Monitor:
  - portainer srv1:
      icon: portainer.png
      server: 192.168.1.90
      href: https://portainer.nanitech.duckdns.org/
      description: Portainer docker containers monitor
      widget:
        type: portainer
        url: https://192.168.1.90:9443
        env: 2
        key: {{HOMEPAGE_VAR_PORTAINER_ACCESS_KEY}}

  - portainer srv2:
      icon: portainer.png
      server: 192.168.1.90
      href: https://portainer.nanitech.duckdns.org/
      description: Portainer docker containers monitor
      widget:
        type: portainer
        url: https://192.168.1.90:9443
        env: 6
        key: {{HOMEPAGE_VAR_PORTAINER_ACCESS_KEY}}

  - dockdge:
      icon: dockge-light.svg
      server: 192.168.1.90
      href: https://dockge.nanitech.duckdns.org/
      description: A docker compose creator