services:
  portainer_edge_agent:
    image: portainer/agent:2.21.2
    container_name: portainer_edge_agent
    restart: always
    environment:
      EDGE: "1"
      EDGE_ID: $EDGE_ID
      EDGE_KEY: $EDGE_KEY
      EDGE_INSECURE_POLL: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
      - portainer_agent_data:/data

volumes:
  portainer_agent_data:
